// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElLink: typeof import('element-plus/es')['ElLink'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm'];
    ElRow: typeof import('element-plus/es')['ElRow'];
    ElTable: typeof import('element-plus/es')['ElTable'];
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
